### ISSUE TITLE
Support for compiling for `x86_64-unknown-linux-musl`

### ISSUE THREAD

**Issue by rjzak** [Arend-Jan/chat-gpt-lib-rs#62]
At present, the default features of `reqwest` uses SSL from the system. However, this isn't available when compiling for Musl. Could you either have Musl targets enable the `native-tls-vendored` feature in `reqwest` or allow this feature to be enabled by a feature flag for this crate?

**Comment by Arend-Jan** [comment]
I will take a look at this problem.
